"""
FAISS vector store for transcript chunks.

The vector store is responsible for:

1. Building a FAISS index from transcript embeddings.
2. Persisting the index to disk.
3. Persisting source metadata separately from the FAISS binary index.
4. Loading an existing index safely.
5. Performing cosine-similarity search.
6. Returning source-traceable TranscriptChunk objects.

The FAISS index itself contains only vectors. Source metadata is stored
separately so that document IDs, timestamps, expert names, and segment IDs
are never lost during retrieval.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import faiss
import numpy as np

from exception import SensorException
from logger import logging

from src.config import Settings, get_settings
from src.models import RetrievalResult, TranscriptChunk

from .embeddings import EmbeddingService, get_embedding_service

logger = logging.getLogger(__name__)


class FAISSVectorStore:
    """
    Persistent FAISS vector store for TranscriptChunk objects.

    Inner-product similarity is used because embeddings generated by
    EmbeddingService are normalized. For normalized vectors:

        inner_product(a, b) == cosine_similarity(a, b)
    """

    INDEX_FILENAME = "transcript.index"
    METADATA_FILENAME = "metadata.json"

    def __init__(
        self,
        embedding_service: EmbeddingService | None = None,
        settings: Settings | None = None,
    ) -> None:
        """
        Initialize the vector store.

        Args:
            embedding_service: Optional embedding service.
            settings: Optional application settings.
        """
        self.settings = settings or get_settings()
        self.embedding_service = (
            embedding_service or get_embedding_service()
        )

        self.storage_path = self.settings.vector_store_path
        self.index_path = self.storage_path / self.INDEX_FILENAME
        self.metadata_path = self.storage_path / self.METADATA_FILENAME

        self._index: faiss.Index | None = None
        self._chunks: list[TranscriptChunk] = []

    @property
    def index(self) -> faiss.Index | None:
        """Return the currently loaded FAISS index."""
        return self._index

    @property
    def chunks(self) -> list[TranscriptChunk]:
        """Return source metadata associated with the FAISS vectors."""
        return list(self._chunks)

    @property
    def is_ready(self) -> bool:
        """
        Return whether the vector store contains a usable index.
        """
        return (
            self._index is not None
            and self._index.ntotal > 0
            and len(self._chunks) == self._index.ntotal
        )

    @property
    def size(self) -> int:
        """Return the number of indexed transcript chunks."""
        if self._index is None:
            return 0

        return int(self._index.ntotal)

    def build(
        self,
        chunks: list[TranscriptChunk],
        persist: bool = True,
    ) -> None:
        """
        Build a new FAISS index from transcript chunks.

        Existing in-memory index data is replaced.

        Args:
            chunks: Transcript chunks to index.
            persist: Whether to save the index and metadata to disk.

        Raises:
            SensorException: If index creation fails.
        """
        try:
            if not chunks:
                raise ValueError(
                    "Cannot build vector store from an empty chunk list."
                )

            texts = [chunk.text for chunk in chunks]

            logger.info(
                "Building FAISS index for %d transcript chunks.",
                len(chunks),
            )

            embeddings = self.embedding_service.embed_documents(texts)

            self._validate_embeddings(embeddings, len(chunks))

            dimension = embeddings.shape[1]

            index = faiss.IndexFlatIP(dimension)
            index.add(np.ascontiguousarray(embeddings))

            self._index = index
            self._chunks = list(chunks)

            logger.info(
                "FAISS index built successfully: %d vectors, dimension=%d",
                index.ntotal,
                dimension,
            )

            if persist:
                self.save()

        except SensorException:
            raise
        except Exception as error:
            logger.exception("Failed to build FAISS vector store.")
            raise SensorException(
                str(error),
                _sys_module(),
            ) from error

    def add(
        self,
        chunks: list[TranscriptChunk],
        persist: bool = True,
    ) -> None:
        """
        Add transcript chunks to an existing index.

        If no index exists, this method builds one.

        Args:
            chunks: Transcript chunks to add.
            persist: Whether to persist the updated index.
        """
        try:
            if not chunks:
                logger.warning("No chunks supplied to vector store add().")
                return

            if self._index is None:
                self.build(chunks, persist=persist)
                return

            texts = [chunk.text for chunk in chunks]
            embeddings = self.embedding_service.embed_documents(texts)

            self._validate_embeddings(embeddings, len(chunks))

            expected_dimension = self._index.d

            if embeddings.shape[1] != expected_dimension:
                raise ValueError(
                    "Embedding dimension does not match existing FAISS "
                    f"index. Expected {expected_dimension}, got "
                    f"{embeddings.shape[1]}."
                )

            self._index.add(np.ascontiguousarray(embeddings))
            self._chunks.extend(chunks)

            logger.info(
                "Added %d chunks to FAISS index. New size: %d",
                len(chunks),
                self._index.ntotal,
            )

            if persist:
                self.save()

        except SensorException:
            raise
        except Exception as error:
            logger.exception("Failed to add chunks to FAISS vector store.")
            raise SensorException(
                str(error),
                _sys_module(),
            ) from error

    def search(
        self,
        query: str,
        top_k: int | None = None,
        min_score: float | None = None,
    ) -> list[RetrievalResult]:
        """
        Search the vector store using semantic similarity.

        Args:
            query: User's natural-language search question.
            top_k: Maximum number of results to return.
            min_score: Optional minimum cosine similarity threshold.

        Returns:
            RetrievalResult objects sorted from highest to lowest score.

        Raises:
            SensorException: If the vector store is not ready or search fails.
        """
        try:
            if not self.is_ready:
                raise RuntimeError(
                    "Vector store is not ready. Build or load an index first."
                )

            if not query or not query.strip():
                raise ValueError("Search query cannot be empty.")

            requested_k = (
                top_k
                if top_k is not None
                else self.settings.retrieval_top_k
            )

            if requested_k <= 0:
                raise ValueError("top_k must be greater than zero.")

            threshold = (
                min_score
                if min_score is not None
                else self.settings.min_retrieval_score
            )

            if not 0.0 <= threshold <= 1.0:
                raise ValueError(
                    "min_score must be between 0.0 and 1.0."
                )

            query_embedding = self.embedding_service.embed_query(query)

            query_vector = np.asarray(
                query_embedding,
                dtype=np.float32,
            ).reshape(1, -1)

            if query_vector.shape[1] != self._index_dimension():
                raise ValueError(
                    "Query embedding dimension does not match the FAISS "
                    "index dimension."
                )

            search_k = min(requested_k, self.size)

            scores, indices = self._index.search(
                np.ascontiguousarray(query_vector),
                search_k,
            )

            results: list[RetrievalResult] = []

            for rank, (score, index_position) in enumerate(
                zip(scores[0], indices[0]),
                start=1,
            ):
                if index_position < 0:
                    continue

                if index_position >= len(self._chunks):
                    logger.warning(
                        "FAISS returned invalid metadata index: %d",
                        index_position,
                    )
                    continue

                similarity = float(score)

                if similarity < threshold:
                    continue

                chunk = self._chunks[index_position]

                results.append(
                    RetrievalResult(
                        chunk=chunk,
                        score=similarity,
                        rank=rank,
                    )
                )

            logger.info(
                "Vector search returned %d result(s) for query: %s",
                len(results),
                self._truncate_for_log(query),
            )

            return results

        except SensorException:
            raise
        except Exception as error:
            logger.exception("FAISS vector search failed.")
            raise SensorException(
                str(error),
                _sys_module(),
            ) from error

    def save(self) -> None:
        """
        Persist the FAISS index and chunk metadata to disk.

        The index and metadata are written separately because FAISS stores
        vectors but does not know about application-level source metadata.
        """
        try:
            if not self.is_ready:
                raise RuntimeError(
                    "Cannot save an empty or incomplete vector store."
                )

            self.storage_path.mkdir(
                parents=True,
                exist_ok=True,
            )

            faiss.write_index(
                self._index,
                str(self.index_path),
            )

            metadata = {
                "version": 1,
                "embedding_model": self.embedding_service.model_name,
                "embedding_dimension": self._index_dimension(),
                "vector_count": self.size,
                "chunks": [
                    chunk.model_dump(mode="json")
                    for chunk in self._chunks
                ],
            }

            self.metadata_path.write_text(
                json.dumps(
                    metadata,
                    ensure_ascii=False,
                    indent=2,
                ),
                encoding="utf-8",
            )

            logger.info(
                "Vector store persisted successfully: %s",
                self.storage_path,
            )

        except SensorException:
            raise
        except Exception as error:
            logger.exception("Failed to persist vector store.")
            raise SensorException(
                str(error),
                _sys_module(),
            ) from error

    def load(self) -> None:
        """
        Load a previously persisted FAISS index and metadata.

        Raises:
            SensorException: If files are missing, malformed, or
                incompatible with the configured embedding model.
        """
        try:
            if not self.index_path.exists():
                raise FileNotFoundError(
                    f"FAISS index not found: {self.index_path}"
                )

            if not self.metadata_path.exists():
                raise FileNotFoundError(
                    f"Vector metadata not found: {self.metadata_path}"
                )

            logger.info(
                "Loading vector store from: %s",
                self.storage_path,
            )

            index = faiss.read_index(str(self.index_path))

            metadata_text = self.metadata_path.read_text(
                encoding="utf-8"
            )

            metadata = json.loads(metadata_text)

            self._validate_loaded_metadata(
                metadata=metadata,
                index=index,
            )

            raw_chunks = metadata.get("chunks", [])

            chunks = [
                TranscriptChunk.model_validate(item)
                for item in raw_chunks
            ]

            if len(chunks) != index.ntotal:
                raise ValueError(
                    "Vector index and metadata count mismatch. "
                    f"Index contains {index.ntotal} vectors but metadata "
                    f"contains {len(chunks)} chunks."
                )

            self._index = index
            self._chunks = chunks

            logger.info(
                "Vector store loaded successfully: %d vectors.",
                index.ntotal,
            )

        except SensorException:
            raise
        except Exception as error:
            logger.exception("Failed to load vector store.")
            raise SensorException(
                str(error),
                _sys_module(),
            ) from error

    def exists_on_disk(self) -> bool:
        """
        Check whether a complete persisted vector store exists.
        """
        return self.index_path.is_file() and self.metadata_path.is_file()

    def clear(self) -> None:
        """
        Clear the in-memory vector store.

        Persisted files are not deleted.
        """
        self._index = None
        self._chunks = []

        logger.info("In-memory vector store cleared.")

    def delete_persisted_store(self) -> None:
        """
        Delete persisted vector-store files.

        This operation is explicit and is not called automatically.
        """
        try:
            for path in (self.index_path, self.metadata_path):
                if path.exists():
                    path.unlink()

            self.clear()

            logger.info(
                "Persisted vector store deleted: %s",
                self.storage_path,
            )

        except Exception as error:
            logger.exception("Failed to delete persisted vector store.")
            raise SensorException(
                str(error),
                _sys_module(),
            ) from error

    def _validate_embeddings(
        self,
        embeddings: np.ndarray,
        expected_count: int,
    ) -> None:
        """
        Validate embedding matrix shape and values.
        """
        if not isinstance(embeddings, np.ndarray):
            raise TypeError(
                "Embedding service must return a NumPy array."
            )

        if embeddings.ndim != 2:
            raise ValueError(
                f"Expected 2D embedding matrix, got shape {embeddings.shape}."
            )

        if embeddings.shape[0] != expected_count:
            raise ValueError(
                "Embedding count does not match chunk count. "
                f"Expected {expected_count}, got {embeddings.shape[0]}."
            )

        if embeddings.shape[1] <= 0:
            raise ValueError("Embedding dimension must be greater than zero.")

        if not np.isfinite(embeddings).all():
            raise ValueError(
                "Embedding matrix contains NaN or infinite values."
            )

    def _validate_loaded_metadata(
        self,
        metadata: dict[str, Any],
        index: faiss.Index,
    ) -> None:
        """
        Validate metadata before accepting a persisted index.
        """
        if not isinstance(metadata, dict):
            raise ValueError("Vector metadata must be a JSON object.")

        stored_model = metadata.get("embedding_model")

        if stored_model != self.embedding_service.model_name:
            raise ValueError(
                "Embedding model mismatch. Persisted index uses "
                f"'{stored_model}', while the application is configured "
                f"for '{self.embedding_service.model_name}'. Rebuild the "
                "vector store with the configured model."
            )

        stored_dimension = metadata.get("embedding_dimension")

        if stored_dimension != index.d:
            raise ValueError(
                "Stored embedding dimension does not match FAISS index."
            )

        if index.ntotal <= 0:
            raise ValueError("Persisted FAISS index is empty.")

    def _index_dimension(self) -> int:
        """Return the dimensionality of the active FAISS index."""
        if self._index is None:
            raise RuntimeError("FAISS index is not initialized.")

        return int(self._index.d)

    @staticmethod
    def _truncate_for_log(value: str, max_length: int = 120) -> str:
        """
        Keep potentially sensitive or lengthy query text manageable in logs.
        """
        normalized = " ".join(value.split())

        if len(normalized) <= max_length:
            return normalized

        return f"{normalized[:max_length - 3]}..."



def _sys_module():
    """Return the active sys module for SensorException."""
    import sys

    return sys


__all__ = [
    "FAISSVectorStore",
]