"""
Cross-expert disagreement and difference analysis.

This module identifies meaningful differences between expert perspectives
without forcing every difference into a binary "agreement/disagreement"
classification.

Supported difference types:

    - direct_disagreement
    - different_emphasis
    - different_experience
    - complementary
    - insufficient_evidence

Important design principles:

    1. Differences must be grounded in transcript evidence.
    2. Expert metadata comes from the application, not the LLM.
    3. Exact quotes must be supported by supplied evidence.
    4. Timestamps are never generated by the model.
    5. A difference in wording is not automatically a disagreement.
    6. If evidence does not establish a meaningful difference, the result
       should be omitted rather than invented.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any

from exception import SensorException
from logger import logging
from src.analysis.llm import GeminiLLMService, get_llm_service
from src.config import Settings, get_settings
from src.evidence.citation import CitationBuilder
from src.evidence.quote_verifier import QuoteVerifier
from src.models import (
    DifferenceType,
    Disagreement,
    Evidence,
)
from src.retrieval.reranker import RetrievalReranker
from src.retrieval.retriever import Retriever

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class DisagreementAnalysisConfig:
    """
    Configuration for cross-expert difference analysis.
    """

    retrieval_top_k: int
    rerank_top_k: int
    max_differences: int
    minimum_experts: int
    minimum_evidence: int


class DisagreementAnalyzer:
    """
    Analyze differences across expert perspectives.

    The analyzer first retrieves evidence and then asks the grounded LLM
    to classify differences using only the retrieved evidence.

    The LLM is not trusted with source metadata. Evidence indices returned
    by the model are resolved back to application-owned Evidence objects.
    """

    def __init__(
        self,
        retriever: Retriever,
        reranker: RetrievalReranker,
        llm_service: GeminiLLMService | None = None,
        quote_verifier: QuoteVerifier | None = None,
        citation_builder: CitationBuilder | None = None,
        settings: Settings | None = None,
    ) -> None:
        """
        Initialize the disagreement analyzer.
        """
        try:
            self.settings = settings or get_settings()

            self.retriever = retriever
            self.reranker = reranker
            self.llm_service = llm_service or get_llm_service()
            self.quote_verifier = (
                quote_verifier or QuoteVerifier()
            )
            self.citation_builder = (
                citation_builder or CitationBuilder()
            )

            self.config = DisagreementAnalysisConfig(
                retrieval_top_k=self.settings.retrieval_top_k,
                rerank_top_k=self.settings.rerank_top_k,
                max_differences=10,
                minimum_experts=2,
                minimum_evidence=2,
            )

        except Exception as error:
            logger.exception(
                "Failed to initialize DisagreementAnalyzer."
            )
            raise SensorException(
                str(error),
                _sys_module(),
            ) from error

    def analyze(
        self,
        *,
        focus: str | None = None,
        expert_names: Iterable[str] | None = None,
        max_differences: int | None = None,
    ) -> list[Disagreement]:
        """
        Identify grounded differences across expert perspectives.

        Args:
            focus: Optional topic to analyze.
            expert_names: Optional expert scope.
            max_differences: Maximum number of results.

        Returns:
            List of Disagreement objects.
        """
        try:
            normalized_experts = self._normalize_experts(
                expert_names
            )

            query = self._build_difference_query(
                focus=focus
            )

            retrieval_results = self.retriever.retrieve(
                query=query,
                top_k=self.config.retrieval_top_k,
            )

            reranked_results = self.reranker.rerank_by_expert_balance(
                query=query,
                results=retrieval_results,
                top_k=self.config.rerank_top_k,
            )

            evidence = self._results_to_evidence(
                reranked_results
            )

            if normalized_experts:
                evidence = [
                    item
                    for item in evidence
                    if item.expert_name in normalized_experts
                ]

            evidence = self._verify_evidence(
                evidence
            )

            if len(evidence) < self.config.minimum_evidence:
                logger.warning(
                    "Insufficient evidence for difference analysis."
                )
                return []

            experts = {
                item.expert_name
                for item in evidence
                if item.expert_name
            }

            if len(experts) < self.config.minimum_experts:
                logger.warning(
                    "Difference analysis requires evidence from at least "
                    "%s experts.",
                    self.config.minimum_experts,
                )
                return []

            raw_differences = self._generate_differences(
                query=query,
                evidence=evidence,
                max_differences=(
                    max_differences
                    or self.config.max_differences
                ),
            )

            return self._build_disagreement_objects(
                raw_differences=raw_differences,
                evidence=evidence,
            )

        except SensorException:
            raise

        except Exception as error:
            logger.exception(
                "Cross-expert difference analysis failed."
            )
            raise SensorException(
                str(error),
                _sys_module(),
            ) from error

    def analyze_for_question(
        self,
        question: str,
        *,
        expert_names: Iterable[str] | None = None,
        max_differences: int | None = None,
    ) -> list[Disagreement]:
        """
        Identify differences specifically related to a question.
        """
        if not question.strip():
            raise ValueError(
                "Question cannot be empty."
            )

        return self.analyze(
            focus=question,
            expert_names=expert_names,
            max_differences=max_differences,
        )

    def _build_difference_query(
        self,
        focus: str | None,
    ) -> str:
        """
        Build a retrieval query focused on differences between experts.
        """
        if focus and focus.strip():
            return (
                "Find differences, contrasting views, differing emphasis, "
                "different experiences, complementary perspectives, and "
                f"potential disagreements related to: {focus.strip()}"
            )

        return (
            "Find contrasting expert perspectives, disagreements, "
            "different emphasis, different experiences, and complementary "
            "views about robotic surgery adoption, barriers, budgets, ROI, "
            "training, outcomes, future trends, and purchasing timelines."
        )

    def _generate_differences(
        self,
        query: str,
        evidence: list[Evidence],
        max_differences: int,
    ) -> list[dict[str, Any]]:
        """
        Generate difference classifications from grounded evidence.
        """
        prompt = self._build_difference_prompt(
            query=query,
            evidence=evidence,
            max_differences=max_differences,
        )

        response = self.llm_service.generate_json(
            prompt=prompt,
            schema=self._difference_schema(),
        )

        differences = response.get(
            "differences",
            [],
        )

        if not isinstance(differences, list):
            return []

        return [
            item
            for item in differences
            if isinstance(item, dict)
        ]

    def _build_difference_prompt(
        self,
        query: str,
        evidence: list[Evidence],
        max_differences: int,
    ) -> str:
        """
        Build the grounded difference-analysis prompt.
        """
        evidence_block = self._serialize_evidence(
            evidence
        )

        return f"""
Analyze differences between the supplied expert perspectives.

FOCUS:
{query}

MAXIMUM DIFFERENCES:
{max_differences}

CLASSIFICATION DEFINITIONS:

1. direct_disagreement
   Two experts make materially conflicting statements about the same
   issue.

2. different_emphasis
   Experts broadly agree on the issue but emphasize different factors.

3. different_experience
   The difference may reflect different roles, institutions, markets,
   or professional experiences rather than disagreement.

4. complementary
   The expert statements address different aspects that can coexist.

5. insufficient_evidence
   The supplied evidence does not establish a reliable difference.

STRICT RULES:

- Use ONLY the supplied evidence.
- Do not use outside knowledge.
- Do not invent expert statements.
- Do not invent quotes.
- Do not invent timestamps.
- Do not call something a direct disagreement merely because wording
  differs.
- Consider the expert's role and market when interpreting differences.
- A procurement director and a clinician may naturally emphasize
  different dimensions of the same decision.
- Return evidence indices for every expert statement supporting the
  difference.
- Use at least two different experts for a cross-expert difference.
- If there is not enough evidence, omit the difference.
- Do not rank experts.
- Do not determine who is correct.
- Keep the comparison descriptive and evidence-based.

Return JSON only.

EVIDENCE:
{evidence_block}
""".strip()

    @staticmethod
    def _difference_schema() -> dict[str, Any]:
        """
        Return the structured-output schema for difference analysis.
        """
        difference_types = [
            value.value
            for value in DifferenceType
        ]

        return {
            "type": "object",
            "properties": {
                "differences": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "topic": {
                                "type": "string",
                            },
                            "difference_type": {
                                "type": "string",
                                "enum": difference_types,
                            },
                            "summary": {
                                "type": "string",
                            },
                            "evidence_indices": {
                                "type": "array",
                                "items": {
                                    "type": "integer",
                                },
                            },
                        },
                        "required": [
                            "topic",
                            "difference_type",
                            "summary",
                            "evidence_indices",
                        ],
                    },
                }
            },
            "required": ["differences"],
        }

    def _build_disagreement_objects(
        self,
        raw_differences: list[dict[str, Any]],
        evidence: list[Evidence],
    ) -> list[Disagreement]:
        """
        Convert model output into application-owned Disagreement models.
        """
        results: list[Disagreement] = []
        seen: set[str] = set()

        for raw in raw_differences:
            topic = self._clean_text(
                raw.get("topic")
            )

            summary = self._clean_text(
                raw.get("summary")
            )

            if not topic or not summary:
                continue

            difference_type = self._parse_difference_type(
                raw.get("difference_type")
            )

            if difference_type is None:
                continue

            indices = self._safe_indices(
                raw.get("evidence_indices"),
                len(evidence),
            )

            supporting_evidence = [
                evidence[index - 1]
                for index in indices
            ]

            experts = {
                item.expert_name
                for item in supporting_evidence
                if item.expert_name
            }

            if len(experts) < self.config.minimum_experts:
                continue

            evidence_items = self._build_evidence_items(
                supporting_evidence
            )

            if len(evidence_items) < self.config.minimum_evidence:
                continue

            dedupe_key = (
                f"{topic.casefold()}|"
                f"{difference_type.value}|"
                f"{','.join(sorted(experts))}"
            )

            if dedupe_key in seen:
                continue

            seen.add(dedupe_key)

            results.append(
                Disagreement(
                    disagreement_id=self._difference_id(
                        topic=topic,
                        difference_type=difference_type,
                        evidence=supporting_evidence,
                    ),
                    topic=topic,
                    difference_type=difference_type,
                    summary=summary,
                    experts=sorted(experts),
                    evidence=evidence_items,
                )
            )

            if len(results) >= self.config.max_differences:
                break

        return results

    def _build_evidence_items(
        self,
        evidence: list[Evidence],
    ) -> list[Evidence]:
        """
        Validate evidence and return source-grounded evidence items.
        """
        result: list[Evidence] = []
        seen: set[str] = set()

        for item in evidence:
            key = (
                f"{item.document_id}:"
                f"{item.start_timestamp}:"
                f"{item.quote}"
            )

            if key in seen:
                continue

            seen.add(key)
            result.append(item)

        return result

    def _verify_evidence(
        self,
        evidence: list[Evidence],
    ) -> list[Evidence]:
        """
        Verify evidence against source text before analysis.
        """
        verified: list[Evidence] = []

        for item in evidence:
            verification = self.quote_verifier.verify(
                quote=item.quote,
                source_text=item.source_text,
            )

            if not verification.verified:
                logger.warning(
                    "Difference evidence failed verification: %s",
                    item.evidence_id,
                )
                continue

            verified.append(
                item.model_copy(
                    update={
                        "status": verification.status,
                        "verification_message": (
                            verification.reason
                        ),
                    }
                )
            )

        return verified

    def _results_to_evidence(
        self,
        results: list,
    ) -> list[Evidence]:
        """
        Convert retrieval results to application Evidence objects.
        """
        evidence: list[Evidence] = []

        for result in results:
            chunk = result.chunk

            if not chunk.text.strip():
                continue

            evidence.append(
                Evidence(
                    evidence_id=(
                        f"evidence:{chunk.chunk_id}"
                    ),
                    document_id=chunk.document_id,
                    chunk_id=chunk.chunk_id,
                    source_file=chunk.source_file,
                    expert_name=chunk.expert_name,
                    market=chunk.market,
                    speaker=chunk.speaker,
                    start_timestamp=chunk.start_timestamp,
                    end_timestamp=chunk.end_timestamp,
                    quote=chunk.text,
                    source_text=chunk.text,
                )
            )

        return evidence

    @staticmethod
    def _serialize_evidence(
        evidence: list[Evidence],
    ) -> str:
        """
        Serialize source evidence for the LLM.
        """
        blocks: list[str] = []

        for index, item in enumerate(evidence, start=1):
            blocks.append(
                "\n".join(
                    [
                        f"[EVIDENCE {index}]",
                        f"Document ID: {item.document_id}",
                        f"Source file: {item.source_file}",
                        f"Expert: {item.expert_name}",
                        f"Market: {item.market}",
                        f"Timestamp: {item.start_timestamp}",
                        (
                            f"End timestamp: {item.end_timestamp}"
                            if item.end_timestamp
                            else "End timestamp: unavailable"
                        ),
                        f"Text: {item.source_text}",
                    ]
                )
            )

        return "\n\n".join(blocks)

    @staticmethod
    def _normalize_experts(
        expert_names: Iterable[str] | None,
    ) -> set[str]:
        """
        Normalize optional expert names.
        """
        if expert_names is None:
            return set()

        return {
            name.strip()
            for name in expert_names
            if isinstance(name, str) and name.strip()
        }

    @staticmethod
    def _safe_indices(
        values: Any,
        evidence_count: int,
    ) -> list[int]:
        """
        Validate model-generated evidence indices.
        """
        if not isinstance(values, list):
            return []

        valid: list[int] = []
        seen: set[int] = set()

        for value in values:
            try:
                index = int(value)
            except (TypeError, ValueError):
                continue

            if index < 1 or index > evidence_count:
                continue

            if index in seen:
                continue

            seen.add(index)
            valid.append(index)

        return valid

    @staticmethod
    def _parse_difference_type(
        value: Any,
    ) -> DifferenceType | None:
        """
        Safely parse a DifferenceType returned by the LLM.
        """
        if not isinstance(value, str):
            return None

        normalized = value.strip().lower()

        try:
            return DifferenceType(normalized)
        except ValueError:
            return None

    @staticmethod
    def _clean_text(
        value: Any,
    ) -> str:
        """
        Normalize generated descriptive text.
        """
        if not isinstance(value, str):
            return ""

        return " ".join(
            value.split()
        ).strip()

    @staticmethod
    def _difference_id(
        topic: str,
        difference_type: DifferenceType,
        evidence: list[Evidence],
    ) -> str:
        """
        Generate a deterministic difference identifier.
        """
        import hashlib

        experts = sorted(
            {
                item.expert_name
                for item in evidence
                if item.expert_name
            }
        )

        raw = "|".join(
            [
                topic.casefold(),
                difference_type.value,
                *experts,
            ]
        )

        digest = hashlib.sha1(
            raw.encode("utf-8")
        ).hexdigest()[:12]

        return f"difference:{digest}"


def get_disagreement_analyzer(
    retriever: Retriever,
    reranker: RetrievalReranker,
    *,
    llm_service: GeminiLLMService | None = None,
    quote_verifier: QuoteVerifier | None = None,
    citation_builder: CitationBuilder | None = None,
    settings: Settings | None = None,
) -> DisagreementAnalyzer:
    """
    Construct a DisagreementAnalyzer using application defaults.
    """
    return DisagreementAnalyzer(
        retriever=retriever,
        reranker=reranker,
        llm_service=llm_service,
        quote_verifier=quote_verifier,
        citation_builder=citation_builder,
        settings=settings,
    )


def _sys_module():
    """Return the active sys module for SensorException."""
    import sys

    return sys


__all__ = [
    "DisagreementAnalysisConfig",
    "DisagreementAnalyzer",
    "get_disagreement_analyzer",
]