"""
Core domain models for the Hasamex Expert Analysis application.

These models define the structured contracts shared by the ingestion,
retrieval, evidence, and analysis layers.

The application deliberately keeps source metadata attached to every
piece of evidence so that generated answers can be traced back to the
original transcript.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class SpeakerType(str, Enum):
    """Supported transcript speaker types."""

    INTERVIEWER = "interviewer"
    EXPERT = "expert"
    UNKNOWN = "unknown"


class EvidenceStatus(str, Enum):
    """Status of evidence validation."""

    VERIFIED = "verified"
    UNVERIFIED = "unverified"
    REJECTED = "rejected"


class DifferenceType(str, Enum):
    """Classification used when comparing expert viewpoints."""

    DIRECT_DISAGREEMENT = "direct_disagreement"
    DIFFERENT_EMPHASIS = "different_emphasis"
    DIFFERENT_EXPERIENCE = "different_experience"
    COMPLEMENTARY = "complementary"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"


class TranscriptMetadata(BaseModel):
    """Metadata describing one expert transcript."""

    model_config = ConfigDict(extra="forbid")

    document_id: str = Field(
        ...,
        min_length=1,
        description="Stable identifier for the transcript.",
    )

    source_file: str = Field(
        ...,
        min_length=1,
        description="Original transcript filename.",
    )

    expert_name: str = Field(
        ...,
        min_length=1,
        description="Full name of the interviewed expert.",
    )

    expert_role: str = Field(
        ...,
        min_length=1,
        description="Professional role of the expert.",
    )

    market: str = Field(
        ...,
        min_length=1,
        description="Market/country represented by the expert.",
    )


class TranscriptSegment(BaseModel):
    """
    A timestamped speaker segment from an original transcript.

    The parser creates these objects directly from source transcript
    content. Timestamps therefore originate from the source and are
    never generated by the LLM.
    """

    model_config = ConfigDict(extra="forbid")

    segment_id: str = Field(
        ...,
        min_length=1,
        description="Stable identifier for this transcript segment.",
    )

    document_id: str = Field(
        ...,
        min_length=1,
        description="Identifier of the parent transcript.",
    )

    source_file: str = Field(
        ...,
        min_length=1,
        description="Original transcript filename.",
    )

    expert_name: str = Field(
        ...,
        min_length=1,
        description="Expert associated with the transcript.",
    )

    expert_role: str = Field(
        ...,
        min_length=1,
        description="Role of the expert.",
    )

    market: str = Field(
        ...,
        min_length=1,
        description="Market represented by the expert.",
    )

    speaker: str = Field(
        ...,
        min_length=1,
        description="Original speaker label from the transcript.",
    )

    speaker_type: SpeakerType = Field(
        default=SpeakerType.UNKNOWN,
        description="Normalized speaker category.",
    )

    text: str = Field(
        ...,
        min_length=1,
        description="Original transcript text for this segment.",
    )

    start_timestamp: str = Field(
        ...,
        min_length=1,
        description="Source timestamp marking the start of the segment.",
    )

    end_timestamp: str | None = Field(
        default=None,
        description=(
            "Timestamp marking the end of the segment when it can be "
            "determined from the source."
        ),
    )

    start_seconds: int = Field(
        ...,
        ge=0,
        description="Start timestamp converted to seconds.",
    )

    end_seconds: int | None = Field(
        default=None,
        ge=0,
        description="End timestamp converted to seconds when available.",
    )

    @field_validator("text")
    @classmethod
    def normalize_text(cls, value: str) -> str:
        """Remove accidental surrounding whitespace from transcript text."""

        normalized = " ".join(value.split())

        if not normalized:
            raise ValueError("Transcript segment text cannot be empty.")

        return normalized

    @field_validator("end_seconds")
    @classmethod
    def validate_end_seconds(
        cls,
        value: int | None,
        info,
    ) -> int | None:
        """Ensure an explicit end timestamp is not before its start."""

        if value is None:
            return value

        start_seconds = info.data.get("start_seconds")

        if start_seconds is not None and value < start_seconds:
            raise ValueError(
                "end_seconds cannot be earlier than start_seconds."
            )

        return value


class TranscriptChunk(BaseModel):
    """
    A retrieval-ready chunk built from one or more transcript segments.

    Source metadata is intentionally duplicated onto the chunk so it is
    available directly from vector-store metadata after retrieval.
    """

    model_config = ConfigDict(extra="forbid")

    chunk_id: str = Field(
        ...,
        min_length=1,
        description="Stable identifier for the retrieval chunk.",
    )

    document_id: str = Field(
        ...,
        min_length=1,
        description="Identifier of the parent transcript.",
    )

    source_file: str = Field(
        ...,
        min_length=1,
        description="Original transcript filename.",
    )

    expert_name: str = Field(
        ...,
        min_length=1,
        description="Expert associated with the chunk.",
    )

    expert_role: str = Field(
        ...,
        min_length=1,
        description="Role of the expert.",
    )

    market: str = Field(
        ...,
        min_length=1,
        description="Market represented by the expert.",
    )

    speaker: str = Field(
        ...,
        min_length=1,
        description="Primary speaker represented in the chunk.",
    )

    speaker_type: SpeakerType = Field(
        default=SpeakerType.UNKNOWN,
        description="Normalized speaker category.",
    )

    text: str = Field(
        ...,
        min_length=1,
        description="Text indexed for retrieval.",
    )

    segment_ids: list[str] = Field(
        default_factory=list,
        description="Source segments represented in this chunk.",
    )

    start_timestamp: str = Field(
        ...,
        min_length=1,
        description="Timestamp of the first source segment.",
    )

    end_timestamp: str | None = Field(
        default=None,
        description="Timestamp of the final source segment when available.",
    )

    start_seconds: int = Field(
        ...,
        ge=0,
        description="Start timestamp in seconds.",
    )

    end_seconds: int | None = Field(
        default=None,
        ge=0,
        description="End timestamp in seconds when available.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional retrieval metadata.",
    )

    @field_validator("text")
    @classmethod
    def normalize_text(cls, value: str) -> str:
        """Normalize whitespace without changing source wording."""

        normalized = " ".join(value.split())

        if not normalized:
            raise ValueError("Chunk text cannot be empty.")

        return normalized


class RetrievalResult(BaseModel):
    """A transcript chunk returned by the retrieval layer."""

    model_config = ConfigDict(extra="forbid")

    chunk: TranscriptChunk = Field(
        ...,
        description="Retrieved transcript chunk.",
    )

    semantic_score: float = Field(
        default=0.0,
        ge=-1.0,
        le=1.0,
        description="Similarity score returned by semantic retrieval.",
    )

    lexical_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Optional lexical matching score.",
    )

    rerank_score: float | None = Field(
        default=None,
        description="Score assigned by the reranking layer.",
    )

    retrieval_rank: int = Field(
        ...,
        ge=1,
        description="Rank assigned during initial retrieval.",
    )

    rerank_rank: int | None = Field(
        default=None,
        ge=1,
        description="Rank assigned after reranking.",
    )


class Evidence(BaseModel):
    """
    Source evidence used to support an answer.

    The quote must ultimately be verified against the original source
    before it is presented to the user as an exact quotation.
    """

    model_config = ConfigDict(extra="forbid")

    evidence_id: str = Field(
        ...,
        min_length=1,
        description="Stable identifier for this evidence item.",
    )

    document_id: str = Field(
        ...,
        min_length=1,
        description="Transcript identifier.",
    )

    chunk_id: str = Field(
        ...,
        min_length=1,
        description="Source chunk identifier.",
    )

    source_file: str = Field(
        ...,
        min_length=1,
        description="Original transcript filename.",
    )

    expert_name: str = Field(
        ...,
        min_length=1,
        description="Expert attributed to the evidence.",
    )

    expert_role: str = Field(
        ...,
        min_length=1,
        description="Expert's professional role.",
    )

    market: str = Field(
        ...,
        min_length=1,
        description="Market represented by the expert.",
    )

    speaker: str = Field(
        ...,
        min_length=1,
        description="Original source speaker.",
    )

    start_timestamp: str = Field(
        ...,
        min_length=1,
        description="Source start timestamp.",
    )

    end_timestamp: str | None = Field(
        default=None,
        description="Source end timestamp when available.",
    )

    start_seconds: int = Field(
        ...,
        ge=0,
        description="Start timestamp in seconds.",
    )

    end_seconds: int | None = Field(
        default=None,
        ge=0,
        description="End timestamp in seconds when available.",
    )

    quote: str = Field(
        ...,
        min_length=1,
        description="Candidate or verified quotation from the source.",
    )

    source_text: str = Field(
        ...,
        min_length=1,
        description="Original source text used for quote verification.",
    )

    status: EvidenceStatus = Field(
        default=EvidenceStatus.UNVERIFIED,
        description="Current evidence verification status.",
    )

    verification_message: str | None = Field(
        default=None,
        description="Explanation produced by the quote verification layer.",
    )

    @field_validator("quote", "source_text")
    @classmethod
    def normalize_evidence_text(cls, value: str) -> str:
        """Normalize surrounding whitespace while preserving wording."""

        normalized = " ".join(value.split())

        if not normalized:
            raise ValueError("Evidence text cannot be empty.")

        return normalized


class Citation(BaseModel):
    """Human-readable citation metadata attached to an answer."""

    model_config = ConfigDict(extra="forbid")

    citation_id: str = Field(
        ...,
        min_length=1,
        description="Stable citation identifier.",
    )

    evidence_id: str = Field(
        ...,
        min_length=1,
        description="Evidence item referenced by this citation.",
    )

    expert_name: str = Field(
        ...,
        min_length=1,
        description="Expert name.",
    )

    market: str = Field(
        ...,
        min_length=1,
        description="Expert market.",
    )

    source_file: str = Field(
        ...,
        min_length=1,
        description="Original transcript filename.",
    )

    timestamp: str = Field(
        ...,
        min_length=1,
        description="Human-readable source timestamp.",
    )


class InterviewQuestion(BaseModel):
    """An interview-guide question."""

    model_config = ConfigDict(extra="forbid")

    question_id: str = Field(
        ...,
        min_length=1,
        description="Stable identifier for the guide question.",
    )

    question_number: int = Field(
        ...,
        ge=1,
        description="Original question number from the interview guide.",
    )

    question: str = Field(
        ...,
        min_length=1,
        description="Exact interview-guide question.",
    )


class GroundedAnswer(BaseModel):
    """
    Structured answer generated from retrieved transcript evidence.

    The answer itself is generated by the analysis layer, while its
    supporting evidence must reference source material.
    """

    model_config = ConfigDict(extra="forbid")

    question_id: str = Field(
        ...,
        min_length=1,
        description="Interview question identifier.",
    )

    question: str = Field(
        ...,
        min_length=1,
        description="Question being answered.",
    )

    expert_name: str | None = Field(
        default=None,
        description="Expert when this is an expert-specific answer.",
    )

    market: str | None = Field(
        default=None,
        description="Market when this is an expert-specific answer.",
    )

    answer: str = Field(
        ...,
        min_length=1,
        description="Grounded natural-language answer.",
    )

    evidence: list[Evidence] = Field(
        default_factory=list,
        description="Supporting source evidence.",
    )

    citations: list[Citation] = Field(
        default_factory=list,
        description="Source citations attached to the answer.",
    )

    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="System confidence based on evidence quality.",
    )

    coverage: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Estimated evidence coverage of the answer.",
    )

    evidence_sufficient: bool = Field(
        default=False,
        description="Whether available evidence is sufficient.",
    )

    refusal_reason: str | None = Field(
        default=None,
        description=(
            "Reason provided when evidence is insufficient to answer safely."
        ),
    )


class ThemeEvidence(BaseModel):
    """Evidence supporting a cross-transcript theme."""

    model_config = ConfigDict(extra="forbid")

    evidence: Evidence = Field(
        ...,
        description="Source evidence supporting the theme.",
    )

    relevance: str = Field(
        ...,
        min_length=1,
        description="Why this evidence supports the theme.",
    )


class Theme(BaseModel):
    """A common theme identified across expert transcripts."""

    model_config = ConfigDict(extra="forbid")

    theme_id: str = Field(
        ...,
        min_length=1,
        description="Stable theme identifier.",
    )

    name: str = Field(
        ...,
        min_length=1,
        description="Theme name.",
    )

    summary: str = Field(
        ...,
        min_length=1,
        description="Grounded summary of the theme.",
    )

    experts: list[str] = Field(
        default_factory=list,
        description="Experts whose transcripts support the theme.",
    )

    markets: list[str] = Field(
        default_factory=list,
        description="Markets represented in the theme.",
    )

    evidence: list[ThemeEvidence] = Field(
        default_factory=list,
        description="Supporting evidence.",
    )


class ExpertPosition(BaseModel):
    """One expert's position on a comparison topic."""

    model_config = ConfigDict(extra="forbid")

    expert_name: str = Field(
        ...,
        min_length=1,
        description="Expert name.",
    )

    market: str = Field(
        ...,
        min_length=1,
        description="Expert market.",
    )

    position: str = Field(
        ...,
        min_length=1,
        description="Grounded summary of the expert's position.",
    )

    evidence: list[Evidence] = Field(
        default_factory=list,
        description="Evidence supporting the position.",
    )


class Disagreement(BaseModel):
    """A documented difference or comparison between expert viewpoints."""

    model_config = ConfigDict(extra="forbid")

    disagreement_id: str = Field(
        ...,
        min_length=1,
        description="Stable disagreement/comparison identifier.",
    )

    topic: str = Field(
        ...,
        min_length=1,
        description="Topic being compared.",
    )

    difference_type: DifferenceType = Field(
        ...,
        description="Nature of the difference.",
    )

    description: str = Field(
        ...,
        min_length=1,
        description="Grounded description of the difference.",
    )

    positions: list[ExpertPosition] = Field(
        default_factory=list,
        description="Expert positions supporting the comparison.",
    )


class SearchQuery(BaseModel):
    """Normalized user search/query request."""

    model_config = ConfigDict(extra="forbid")

    query: str = Field(
        ...,
        min_length=1,
        description="User's natural-language question.",
    )

    expert_filter: str | None = Field(
        default=None,
        description="Optional expert filter.",
    )

    market_filter: str | None = Field(
        default=None,
        description="Optional market filter.",
    )

    top_k: int | None = Field(
        default=None,
        ge=1,
        description="Optional retrieval result limit.",
    )

    @field_validator("query")
    @classmethod
    def normalize_query(cls, value: str) -> str:
        """Normalize whitespace in a user query."""

        normalized = " ".join(value.split())

        if not normalized:
            raise ValueError("Query cannot be empty.")

        return normalized


class EvaluationCase(BaseModel):
    """One manually verified evaluation case."""

    model_config = ConfigDict(extra="forbid")

    case_id: str = Field(
        ...,
        min_length=1,
        description="Unique evaluation case identifier.",
    )

    question: str = Field(
        ...,
        min_length=1,
        description="Evaluation question.",
    )

    expected_experts: list[str] = Field(
        default_factory=list,
        description="Experts expected to provide relevant evidence.",
    )

    expected_markets: list[str] = Field(
        default_factory=list,
        description="Markets expected to provide relevant evidence.",
    )

    expected_keywords: list[str] = Field(
        default_factory=list,
        description="Important concepts expected in supporting evidence.",
    )

    expected_source_files: list[str] = Field(
        default_factory=list,
        description="Source files expected to support the answer.",
    )


class EvaluationResult(BaseModel):
    """Result of evaluating one evaluation case."""

    model_config = ConfigDict(extra="forbid")

    case_id: str = Field(
        ...,
        min_length=1,
        description="Evaluation case identifier.",
    )

    retrieval_relevance: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    citation_correctness: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    timestamp_correctness: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    quote_correctness: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    groundedness: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    completeness: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    notes: list[str] = Field(
        default_factory=list,
        description="Evaluation notes.",
    )


class ApplicationStats(BaseModel):
    """Runtime statistics displayed by the application dashboard."""

    model_config = ConfigDict(extra="forbid")

    transcript_count: int = Field(
        default=0,
        ge=0,
    )

    expert_count: int = Field(
        default=0,
        ge=0,
    )

    question_count: int = Field(
        default=0,
        ge=0,
    )

    indexed_chunk_count: int = Field(
        default=0,
        ge=0,
    )

    theme_count: int = Field(
        default=0,
        ge=0,
    )

    disagreement_count: int = Field(
        default=0,
        ge=0,
    )