"""
Timestamp-aware transcript chunking.

This module converts parsed TranscriptSegment objects into
TranscriptChunk objects suitable for embedding and retrieval.

The chunker preserves:
    - document identity
    - source filename
    - expert metadata
    - market
    - speaker
    - speaker type
    - source segment IDs
    - timestamp boundaries
    - structured metadata

No timestamps or source information are generated by the chunker.
"""

from __future__ import annotations

from typing import Final

from exception import SensorException
from logger import logging
from src.models import TranscriptChunk, TranscriptSegment

logger = logging.getLogger(__name__)


DEFAULT_CHUNK_SIZE: Final[int] = 1200
DEFAULT_CHUNK_OVERLAP: Final[int] = 200


class TranscriptChunker:
    """
    Create source-traceable chunks from transcript segments.

    Chunk boundaries are based on character length, but the chunker
    prefers to keep complete transcript segments together whenever
    possible.

    All source metadata is inherited directly from the original
    TranscriptSegment objects.
    """

    def __init__(
        self,
        chunk_size: int = DEFAULT_CHUNK_SIZE,
        chunk_overlap: int = DEFAULT_CHUNK_OVERLAP,
    ) -> None:
        """
        Initialize the chunker.

        Args:
            chunk_size:
                Maximum target number of characters per chunk.

            chunk_overlap:
                Number of characters to carry into the next chunk
                when a split is required.

        Raises:
            ValueError:
                If the configuration is invalid.
        """
        if chunk_size <= 0:
            raise ValueError(
                "chunk_size must be greater than zero."
            )

        if chunk_overlap < 0:
            raise ValueError(
                "chunk_overlap cannot be negative."
            )

        if chunk_overlap >= chunk_size:
            raise ValueError(
                "chunk_overlap must be smaller than chunk_size."
            )

        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap

    def chunk(
        self,
        segments: list[TranscriptSegment],
    ) -> list[TranscriptChunk]:
        """
        Convert transcript segments into retrieval-ready chunks.

        Args:
            segments:
                Ordered timestamp-aware transcript segments.

        Returns:
            List of source-traceable TranscriptChunk objects.

        Raises:
            SensorException:
                If chunking fails.
        """
        try:
            if not segments:
                logger.warning(
                    "No transcript segments supplied for chunking."
                )
                return []

            ordered_segments = (
                self._validate_and_sort_segments(
                    segments
                )
            )

            chunks = self._build_chunks(
                ordered_segments
            )

            logger.info(
                "Created %d retrieval chunks from %d "
                "transcript segments.",
                len(chunks),
                len(ordered_segments),
            )

            return chunks

        except SensorException:
            raise

        except Exception as error:
            logger.exception(
                "Failed to chunk transcript segments."
            )

            raise SensorException(
                str(error),
                _sys_module(),
            ) from error

    def _build_chunks(
        self,
        segments: list[TranscriptSegment],
    ) -> list[TranscriptChunk]:
        """
        Build chunks while retaining source segment boundaries.
        """
        chunks: list[TranscriptChunk] = []

        buffer_segments: list[
            TranscriptSegment
        ] = []

        buffer_text = ""

        for segment in segments:
            segment_text = self._format_segment(
                segment
            )

            if not segment_text:
                continue

            candidate_text = self._join_text(
                buffer_text,
                segment_text,
            )

            if (
                buffer_segments
                and len(candidate_text) > self.chunk_size
            ):
                chunk = self._create_chunk(
                    chunk_index=len(chunks),
                    segments=buffer_segments,
                    text=buffer_text,
                )

                chunks.append(chunk)

                overlap_segments = (
                    self._select_overlap_segments(
                        buffer_segments
                    )
                )

                buffer_segments = overlap_segments

                buffer_text = self._join_segments(
                    overlap_segments
                )

                candidate_text = self._join_text(
                    buffer_text,
                    segment_text,
                )

            if (
                len(candidate_text) > self.chunk_size
                and not buffer_segments
            ):
                split_chunks = (
                    self._split_large_segment(
                        segment=segment,
                        starting_index=len(chunks),
                    )
                )

                chunks.extend(split_chunks)

                buffer_segments = []
                buffer_text = ""

                continue

            buffer_segments.append(segment)
            buffer_text = candidate_text

        if buffer_segments:
            chunks.append(
                self._create_chunk(
                    chunk_index=len(chunks),
                    segments=buffer_segments,
                    text=buffer_text,
                )
            )

        return chunks

    def _create_chunk(
        self,
        chunk_index: int,
        segments: list[TranscriptSegment],
        text: str,
    ) -> TranscriptChunk:
        """
        Create a TranscriptChunk from source segments.
        """
        if not segments:
            raise ValueError(
                "Cannot create a chunk without source segments."
            )

        first = segments[0]
        last = segments[-1]

        return TranscriptChunk(
            chunk_id=(
                f"{first.document_id}"
                f"-chunk-{chunk_index + 1:04d}"
            ),
            document_id=first.document_id,
            source_file=first.source_file,
            expert_name=first.expert_name,
            expert_role=first.expert_role,
            market=first.market,
            speaker=first.speaker,
            speaker_type=first.speaker_type,
            text=text.strip(),
            segment_ids=[
                segment.segment_id
                for segment in segments
            ],
            start_timestamp=first.start_timestamp,
            end_timestamp=last.end_timestamp,
            start_seconds=first.start_seconds,
            end_seconds=last.end_seconds,
            metadata={
                "document_id": first.document_id,
                "source_file": first.source_file,
                "expert_name": first.expert_name,
                "expert_role": first.expert_role,
                "market": first.market,
                "speaker": first.speaker,
                "speaker_type": (
                    first.speaker_type.value
                    if hasattr(
                        first.speaker_type,
                        "value",
                    )
                    else str(first.speaker_type)
                ),
                "segment_ids": [
                    segment.segment_id
                    for segment in segments
                ],
                "start_timestamp": (
                    first.start_timestamp
                ),
                "end_timestamp": (
                    last.end_timestamp
                ),
                "start_seconds": (
                    first.start_seconds
                ),
                "end_seconds": (
                    last.end_seconds
                ),
            },
        )

    def _split_large_segment(
        self,
        segment: TranscriptSegment,
        starting_index: int,
    ) -> list[TranscriptChunk]:
        """
        Split an unusually large individual transcript segment.

        Source metadata remains attached to every resulting chunk.

        No artificial timestamp is introduced.
        """
        text = segment.text.strip()

        if len(text) <= self.chunk_size:
            return [
                self._create_chunk(
                    chunk_index=starting_index,
                    segments=[segment],
                    text=text,
                )
            ]

        pieces = self._split_text(
            text=text,
            max_length=self.chunk_size,
            overlap=self.chunk_overlap,
        )

        chunks: list[TranscriptChunk] = []

        for offset, piece in enumerate(pieces):
            chunks.append(
                TranscriptChunk(
                    chunk_id=(
                        f"{segment.document_id}"
                        f"-chunk-"
                        f"{starting_index + offset + 1:04d}"
                    ),
                    document_id=segment.document_id,
                    source_file=segment.source_file,
                    expert_name=segment.expert_name,
                    expert_role=segment.expert_role,
                    market=segment.market,
                    speaker=segment.speaker,
                    speaker_type=segment.speaker_type,
                    text=piece,
                    segment_ids=[
                        segment.segment_id
                    ],
                    start_timestamp=(
                        segment.start_timestamp
                    ),
                    end_timestamp=(
                        segment.end_timestamp
                    ),
                    start_seconds=(
                        segment.start_seconds
                    ),
                    end_seconds=(
                        segment.end_seconds
                    ),
                    metadata={
                        "document_id": (
                            segment.document_id
                        ),
                        "source_file": (
                            segment.source_file
                        ),
                        "expert_name": (
                            segment.expert_name
                        ),
                        "expert_role": (
                            segment.expert_role
                        ),
                        "market": segment.market,
                        "speaker": segment.speaker,
                        "speaker_type": (
                            segment.speaker_type.value
                            if hasattr(
                                segment.speaker_type,
                                "value",
                            )
                            else str(
                                segment.speaker_type
                            )
                        ),
                        "segment_ids": [
                            segment.segment_id
                        ],
                        "start_timestamp": (
                            segment.start_timestamp
                        ),
                        "end_timestamp": (
                            segment.end_timestamp
                        ),
                        "start_seconds": (
                            segment.start_seconds
                        ),
                        "end_seconds": (
                            segment.end_seconds
                        ),
                    },
                )
            )

        return chunks

    def _select_overlap_segments(
        self,
        segments: list[TranscriptSegment],
    ) -> list[TranscriptSegment]:
        """
        Select complete source segments for overlap.

        Complete segments are preferred over cutting source metadata
        across arbitrary character boundaries.
        """
        if self.chunk_overlap <= 0:
            return []

        selected: list[TranscriptSegment] = []
        current_length = 0

        for segment in reversed(segments):
            segment_length = len(
                self._format_segment(segment)
            )

            if (
                selected
                and current_length + segment_length
                > self.chunk_overlap
            ):
                break

            selected.insert(0, segment)
            current_length += segment_length

            if current_length >= self.chunk_overlap:
                break

        return selected

    def _validate_and_sort_segments(
        self,
        segments: list[TranscriptSegment],
    ) -> list[TranscriptSegment]:
        """
        Validate that segments belong to a coherent transcript
        and return them in timestamp order.
        """
        document_ids = {
            segment.document_id
            for segment in segments
        }

        if len(document_ids) > 1:
            raise ValueError(
                "All segments supplied to one chunking "
                "operation must belong to the same document."
            )

        source_files = {
            segment.source_file
            for segment in segments
        }

        if len(source_files) > 1:
            raise ValueError(
                "All segments supplied to one chunking "
                "operation must belong to the same source file."
            )

        ordered = sorted(
            segments,
            key=lambda segment: (
                segment.start_seconds,
                segment.segment_id,
            ),
        )

        return ordered

    def _format_segment(
        self,
        segment: TranscriptSegment,
    ) -> str:
        """
        Format a source segment for semantic retrieval.

        Timestamp and speaker metadata are included in the text
        so retrieved context remains understandable to the LLM.
        """
        timestamp = segment.start_timestamp
        speaker = segment.speaker or "Unknown"

        return (
            f"[{timestamp}] "
            f"{speaker}: "
            f"{segment.text.strip()}"
        )

    @staticmethod
    def _join_text(
        left: str,
        right: str,
    ) -> str:
        """Join two chunk fragments with a separator."""
        if not left:
            return right

        if not right:
            return left

        return f"{left}\n{right}"

    def _join_segments(
        self,
        segments: list[TranscriptSegment],
    ) -> str:
        """Join source segments using the standard retrieval format."""
        return "\n".join(
            self._format_segment(segment)
            for segment in segments
            if segment.text.strip()
        )

    def _split_text(
        self,
        text: str,
        max_length: int,
        overlap: int,
    ) -> list[str]:
        """
        Split text into overlapping pieces while preferring
        word boundaries.

        This method is used only when one source segment itself
        exceeds the configured chunk size.
        """
        if len(text) <= max_length:
            return [text]

        pieces: list[str] = []

        start = 0
        text_length = len(text)

        while start < text_length:
            end = min(
                start + max_length,
                text_length,
            )

            if end < text_length:
                boundary = text.rfind(
                    " ",
                    start,
                    end,
                )

                if boundary > start:
                    end = boundary

            piece = text[start:end].strip()

            if piece:
                pieces.append(piece)

            if end >= text_length:
                break

            next_start = end - overlap

            if next_start <= start:
                next_start = end

            start = next_start

        return pieces


def _sys_module():
    """Return the active sys module for SensorException."""
    import sys

    return sys


__all__ = [
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_CHUNK_SIZE",
    "TranscriptChunker",
]